spring.application.name=AlerteServer
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/api_database
spring.datasource.username=devuser
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.security.user.name=user
spring.security.user.password=password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dacvigilance@gmail.com
spring.mail.password=toqntwyjtvquczuv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

alerte.niveaux.actifs=1,2,3,4
alerte.types.actifs=1,2,3,4,5,6,7,8,9
alerte.mail.cron=0 0 8 * * *
alerte.update.cron=0 0 6 * * *